### ISSUE TITLE
Upgrading to Rails 7.1 produces WARNING message

### ISSUE THREAD

**Issue by scott-knight** [pawurb/rails-brotli-cache#17]
## The issue

I recently upgraded to Rails 7.1. I found, when I start the Rails console I get this error:

```zsh
DEPRECATION WARNING: Support for `config.active_support.cache_format_version = 6.1` has been deprecated and will be removed in Rails 7.2. ...
called from new at ... /config/environments/development.rb:28
```

Here's what's in my `development.rb` at line 28 -- ` ActiveSupport::Cache::RedisCacheStore.new`:

```ruby
    config.cache_store = RailsBrotliCache::Store.new(
      ActiveSupport::Cache::RedisCacheStore.new(
        url: ENV['REDISCLOUD_URL'],
        size: 30.megabytes
      )
    )
```

After digging a bit into the code calls, I found [RailsBrotliCache::Store](https://github.com/pawurb/rails-brotli-cache/blob/main/lib/rails-brotli-cache/store.rb) inherits from `::ActiveSupport::Cache::Store`. When it instantiates, it's setting the `format_version` based on the inherited value set in `ActiveSupport::Cache::Store`.

Looking at [ActiveSupport::Cache::Store](https://github.com/rails/rails/blob/682854640e6e375bc543313a2f03a8753412a51b/activesupport/lib/active_support/cache.rb#L55), it's setting `@format_version = 6.1`. This hardcoded setting is overriding my app default setting in config/application.rb, which is set to use format_version `7.1` via `config.load_defaults 7.1`. 

### Upgrade Info
In the [Rails upgrade guide](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#new-activesupport-cache-serialization-format), it states there is a new `ActiveSupport::Cache serialization format`. To use it, you simply set the value in `config/application.rb`.  In the case of my project, I'm loading the 7.1 defaults, which will use the new format. 

I'm not sure how you solve this issue. It appears that there may be 2 possible fixes:

1. It would be great if `RailsBrotliCache::Store` was able to honor the project defaults set in `config/application.rb`
2. if it was possible to pass the format_version value when instantiating `RailsBrotliCache::Store` as a wrapper around the `ActiveSupport::Cache::RedisCacheStore.new`.

**Comment by pawurb** [comment]
Thanks for reporting. But I'm getting the same deprecation warning when using standard cache stores. I think it's something that has to be fixed in `ActiveSupport::Cache::Store` and not rails-brotli-cache.
