### ISSUE TITLE
How to use with solid_cache ?

### ISSUE THREAD

**Issue by 34code** [pawurb/rails-brotli-cache#18]
I currently use solid_cache like so:

```config.cache_store = :solid_cache_store```

in `config/environments/development.rb`

How can I use this gem and brotli compression alongside solid_cache?

**Comment by pawurb** [comment]
Hi. I think it might work like:

```
config.cache_store =  RailsBrotliCache::Store.new(Store::SolidCache.new)
```

but I've never tested it with this gem.

**Comment by 34code** [comment]
that worked! thank you :) seems like its working.. noticing slightly lower `value` sizes in `solid_cache_entries` table

**Comment by pawurb** [comment]
Awesome! :)

**Comment by 34code** [comment]
Seems like rails 7.2 doesn't like it?

```DEPRECATION WARNING: Support for `config.active_support.cache_format_version = 6.1` has been deprecated and will be removed in Rails 7.2.```

**Comment by pawurb** [comment]
Please see https://github.com/pawurb/rails-brotli-cache/issues/17
