### ISSUE TITLE
Rails 8 compatibility?

### ISSUE THREAD

**Issue by aseroff** [pawurb/rails-brotli-cache#21]
Hi,

I'm experiencing what may be a compatibility issue between this gem and Rails 8. Switching out `RailsBrotliCache::Store.new(ActiveSupport::Cache::RedisCacheStore.new(url: 'redis://localhost:6379/1'))` with just `ActiveSupport::Cache::RedisCacheStore.new(url: 'redis://localhost:6379/1')` clears up the problem immediately.

Here's the stack trace:
```
NoMethodError: undefined method `transform_keys' for an instance of Array
/usr/local/rvm/gems/ruby-3.3.6/gems/activesupport-8.0.0/lib/active_support/cache.rb:555:in `write_multi'
/usr/local/rvm/gems/ruby-3.3.6/gems/rails-brotli-cache-0.6.2/lib/rails-brotli-cache/store.rb:94:in `write_multi'
```

**Comment by pawurb** [comment]
Rails 8 has this feature built in. Once they update the docs I'll mention it in readme: https://github.com/rails/rails/pull/53036
