### ISSUE TITLE
Cache versioning not supported

### ISSUE THREAD

**Issue by spacebat** [pawurb/rails-brotli-cache#3]
I thought I'd give this gem a go but ran into this error when starting Rails:

```
(RuntimeError)
You're using a cache store that doesn't support native cache versioning.
Your best option is to upgrade to a newer version of RailsBrotliCache::Store
that supports cache versioning (RailsBrotliCache::Store.supports_cache_versioning? #=> true).

Next best, switch to a different cache store that does support cache versioning:
https://guides.rubyonrails.org/caching_with_rails.html#cache-stores.

To keep using the current cache store, you can turn off cache versioning entirely:

    config.active_record.cache_versioning = false
```

Could this be a misconfiguration on my part, or is this a known shortcoming that will either be fixed or documented?

Thanks for this interesting gem.

**Comment by pawurb** [comment]
@spacebat thanks for pointing out. Brotli cache store delegates cache versioning to underlying stores, so only method declaration was missing. It's now fixed in `0.3.4`. Please confirm if it now works for you.
